name = "my-portfolio"
compatibility_date = "2024-07-27"

[build]
command = "npm run build"
cwd = "."
watch_dir = "."
upload_dir = "./build/client"
pages_build_output_dir = "./public"
pages_build_output_dir = "build/client"
